language: node_js
node_js:
  - node
before_install: cd piktorlog
script:
  - npm test
notifications:
email:
  - brandon.g.elzy@gmail.com
  - e.sarragalugo@gmail.com
on_success: never
on_failure: always